[theme]
base = "light"
primaryColor = "#228B22"  # Forest Green 🌳
backgroundColor = "#F7FBEA"  # Very light green
secondaryBackgroundColor = "#FFFFFF"
textColor = "#365314"  # Dark olive green
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 8501

[client]
toolbarMode = "minimal"
showSidebarNavigation = true
