[theme]
base="light"
primaryColor="#365314"
backgroundColor="#F7FBEA"
secondaryBackgroundColor="#E2EFD9"
textColor="#365314"
font="sans serif"

[server]
headless = true
port = 8501
enableCORS = false
